# 方法一 直接输入序列
sequence = "> ACGTCACCACAAACGGAGACTAAAGCGAGTGTTGGATTCAAAGCTGGCGTTAAAGATTACAGATTAAATTATTATACTCCTGATTATAAGACCAAAGACACCGATATTCTGGCAGCATTCCGAATGACTCCCCAACCCGGAGTACCACCTGAGGAAGCAGGAGCCGCAGTAGCTGCTGAATCTTCCACCGGTACATGGACCACTGTCTGGACCGATGGACTTACTAGCCTTGATCGTTACAAAGGTCGATGCTATGACATCGAACCCGTTGCTGGAGAAGAAAATCAATATATTGCCTATGTAGCTTATCCTTTGGATCTGTTCGAGGAAGGTTCTGTTACTAACATGTTCACTTCCATTGTAGGTAATGTATTTGGATTTAAAGCCTTACGAGCTCTACGTTTGGAAGATTTGCGAATTCCTCCTGCATATTCCAAAACCTTCCAAGGTCCACCTCACGGTATCCAAGTTGAAAGAGATAAATTGAACAAATATGGTCGTCCTTTATTGGGATGTACTATTAAACCGAAATTAGGTTTATCCGCTAAAAACTACGGTAGAGCAGTGTATGAATGTCTTCGTGGTGGACTTGATTTTACTAAAGATGATGAAAACGTAAATTCTCAACCGTTTATGCGTTGGAGAGACCGTTTCTTATTCGTAGCAGAAGCTCTTAATAAATCTCAAGCGGAAACGGGTGAGATTAAGGGTCATTACCTGAATGCTACCGCAGGTACATGTGAGGAAATGATGAAAAGGGCGGTATTCGCTAGAGAATTGGGAGCGCCTATTGTCATGCATGACTATTTGACAGGGGGTTTTACTGCAAATACTAGTTTAGCCCATTATTGTCGGGACAATGGTCTACTCCTTCACATTCACCGTGCAATGCATGCTGTTATTGACAGACAGAGAAACCATGGTATTCACTTCCGTGTATTAGCTAAAGCATTGCGTATGTCCGGTGGGGATCACATTCACTCCGGTACTGTGGTGGGTAAACTTGAAGGGGAACGTGAAGTAACTTTAGGTTTTGTTGATCTACTTCGTGACGACTACATTGAAAAAGACCGAAGTCGTGGTATTTATTTTACCCAAGATTGGGTATCTATGCCTGGTGTTTTGCCTGTAGCTTCAGGGGGTATTCACGTTTGGCATATGCCCGCTCTGACCGAAATCTTTGGAGATGATTCTGTATTACAATTTGGTGGTGGAACTTTGGGACACCCCTGGGGGAATGCACCAGGTGCAGTAGCTAACCGAGTTGCTTCAGAAGCTTGTGTACAAGCTCGTAACGAAGGACGTGATCTTGCTCGTGAAGGTAATGAGATTATTCGCGAAGCTTGTAAATGGAGTCCTGAACTAGCTGCTGCTTGCGAAGTATGGAAAGAAATCAAGTTTGAATTTGAGACGATTGACACACTGTAA"

count_A = sequence.count("A")
count_T = sequence.count("T")
count_C = sequence.count("C")
count_G = sequence.count("G")

print("A count:", count_A)
print("T count:", count_T)
print("C count:", count_C)
print("G count:", count_G)

# 方法二 输入文件
filename = "sequence.txt"  # 替换为你的文件名

# 从文件中读取序列
with open(filename, "r") as file:
    sequence = file.read().strip()

count_A = sequence.count("A")
count_T = sequence.count("T")
count_C = sequence.count("C")
count_G = sequence.count("G")

print("A count:", count_A)
print("T count:", count_T)
print("C count:", count_C)
print("G count:", count_G)

# 去除基因名称中的ATCG
filename = "sequence.txt"  # 替换为你的文件名

# 从文件中读取序列
with open(filename, "r") as file:
    lines = file.readlines()

sequence = ""
for line in lines:
    line = line.strip()
    if line.startswith(">"):
        continue  # 跳过基因名称行
    sequence += line

count_A = sequence.count("A")
count_T = sequence.count("T")
count_C = sequence.count("C")
count_G = sequence.count("G")

print("A count:", count_A)
print("T count:", count_T)
print("C count:", count_C)
print("G count:", count_G)





























